### ISSUE TITLE
ordinal not in range error

### ISSUE THREAD

**Issue by ClarkGeek** [yuha0/applechecker#5]
when running the following command `python stock.py "MN9H2LL/A" "96816" "1234567890" 10` I get the following error message.

> Traceback (most recent call last):
>   File "stock.py", line 108, in <module>
>     main(*sys.argv[1:])
>   File "stock.py", line 56, in main
>     store=sname, item=item, buy=BUY, model=model)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)

I have tried several different model numbers and zip codes and i always get the same error

**Comment by yuha0** [comment]
I am assuming all of them are `iPhone 7`s? 
Just found out Apple put a non-breaking space between `iPhone` and `7`, interesting...
Working on it
